services:
  - type: web
    name: tuttibot-backend
    runtime: python
    pythonVersion: 3.10
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT -t 300 app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
